theme: jekyll-theme-minimal
title: CIT - Lab 5
description: I downloaded and installed Postman, created a CIT 281 collection and folders, created a Node.js and fastify server application with GET and respond with JSON, added arrays of student objects, used Postman to test server GET routes, added POST handling to server application and respond with JSON, used Postman and POST request.
